// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Rand is an autogenerated mock type for the Rand type
type Rand struct {
	mock.Mock
}

// Intn provides a mock function with given fields: n
func (_m *Rand) Intn(n int) int {
	ret := _m.Called(n)

	if len(ret) == 0 {
		return 0
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}


