packages:
  github.com/BearBump/TrackBox/internal/services/trackings:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks.go"
      outpkg: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      Repository:

  github.com/BearBump/TrackBox/internal/cache:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks.go"
      outpkg: "mocks"
      structname: "{{.InterfaceName}}"
    interfaces:
      BytesCache: