FROM golang:1.25 AS build
WORKDIR /src

COPY go.mod go.sum ./
COPY internal/pb/go.mod internal/pb/go.sum ./internal/pb/
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/track-worker ./cmd/track-worker

FROM gcr.io/distroless/base-debian12:nonroot
WORKDIR /app

COPY --from=build /out/track-worker /app/track-worker
COPY config.trackbox.docker.yaml /app/config.yaml

ENV configPath=/app/config.yaml

ENTRYPOINT ["/app/track-worker"]


