// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/tracking_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackingEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrackingId uint64                 `protobuf:"varint,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Status     string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusRaw  string                 `protobuf:"bytes,4,opt,name=status_raw,json=statusRaw,proto3" json:"status_raw,omitempty"`
	EventTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	Location   string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Message    string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	// В protobuf это string (JSON), чтобы не тащить structpb/any.
	PayloadJson   string                 `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_models_tracking_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_models_tracking_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_models_tracking_model_proto_rawDescGZIP(), []int{0}
}

func (x *TrackingEvent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TrackingEvent) GetTrackingId() uint64 {
	if x != nil {
		return x.TrackingId
	}
	return 0
}

func (x *TrackingEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrackingEvent) GetStatusRaw() string {
	if x != nil {
		return x.StatusRaw
	}
	return ""
}

func (x *TrackingEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *TrackingEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TrackingEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrackingEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *TrackingEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Tracking struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CarrierCode    string                 `protobuf:"bytes,2,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	TrackNumber    string                 `protobuf:"bytes,3,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StatusRaw      string                 `protobuf:"bytes,5,opt,name=status_raw,json=statusRaw,proto3" json:"status_raw,omitempty"`
	StatusAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=status_at,json=statusAt,proto3" json:"status_at,omitempty"`
	LastCheckedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
	NextCheckAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_check_at,json=nextCheckAt,proto3" json:"next_check_at,omitempty"`
	CheckFailCount int32                  `protobuf:"varint,9,opt,name=check_fail_count,json=checkFailCount,proto3" json:"check_fail_count,omitempty"`
	LastError      string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tracking) Reset() {
	*x = Tracking{}
	mi := &file_models_tracking_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracking) ProtoMessage() {}

func (x *Tracking) ProtoReflect() protoreflect.Message {
	mi := &file_models_tracking_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracking.ProtoReflect.Descriptor instead.
func (*Tracking) Descriptor() ([]byte, []int) {
	return file_models_tracking_model_proto_rawDescGZIP(), []int{1}
}

func (x *Tracking) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tracking) GetCarrierCode() string {
	if x != nil {
		return x.CarrierCode
	}
	return ""
}

func (x *Tracking) GetTrackNumber() string {
	if x != nil {
		return x.TrackNumber
	}
	return ""
}

func (x *Tracking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tracking) GetStatusRaw() string {
	if x != nil {
		return x.StatusRaw
	}
	return ""
}

func (x *Tracking) GetStatusAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusAt
	}
	return nil
}

func (x *Tracking) GetLastCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckedAt
	}
	return nil
}

func (x *Tracking) GetNextCheckAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextCheckAt
	}
	return nil
}

func (x *Tracking) GetCheckFailCount() int32 {
	if x != nil {
		return x.CheckFailCount
	}
	return 0
}

func (x *Tracking) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Tracking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tracking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TrackingCreateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarrierCode   string                 `protobuf:"bytes,1,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	TrackNumber   string                 `protobuf:"bytes,2,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingCreateInput) Reset() {
	*x = TrackingCreateInput{}
	mi := &file_models_tracking_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingCreateInput) ProtoMessage() {}

func (x *TrackingCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_models_tracking_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingCreateInput.ProtoReflect.Descriptor instead.
func (*TrackingCreateInput) Descriptor() ([]byte, []int) {
	return file_models_tracking_model_proto_rawDescGZIP(), []int{2}
}

func (x *TrackingCreateInput) GetCarrierCode() string {
	if x != nil {
		return x.CarrierCode
	}
	return ""
}

func (x *TrackingCreateInput) GetTrackNumber() string {
	if x != nil {
		return x.TrackNumber
	}
	return ""
}

var File_models_tracking_model_proto protoreflect.FileDescriptor

const file_models_tracking_model_proto_rawDesc = "" +
	"\n" +
	"\x1bmodels/tracking_model.proto\x12\x12trackbox.models.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x02\n" +
	"\rTrackingEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\x04R\n" +
	"trackingId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"status_raw\x18\x04 \x01(\tR\tstatusRaw\x129\n" +
	"\n" +
	"event_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12!\n" +
	"\fpayload_json\x18\b \x01(\tR\vpayloadJson\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x93\x04\n" +
	"\bTracking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fcarrier_code\x18\x02 \x01(\tR\vcarrierCode\x12!\n" +
	"\ftrack_number\x18\x03 \x01(\tR\vtrackNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"status_raw\x18\x05 \x01(\tR\tstatusRaw\x127\n" +
	"\tstatus_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bstatusAt\x12B\n" +
	"\x0flast_checked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastCheckedAt\x12>\n" +
	"\rnext_check_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vnextCheckAt\x12(\n" +
	"\x10check_fail_count\x18\t \x01(\x05R\x0echeckFailCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"[\n" +
	"\x13TrackingCreateInput\x12!\n" +
	"\fcarrier_code\x18\x01 \x01(\tR\vcarrierCode\x12!\n" +
	"\ftrack_number\x18\x02 \x01(\tR\vtrackNumberB1Z/github.com/BearBump/TrackBox/internal/pb/modelsb\x06proto3"

var (
	file_models_tracking_model_proto_rawDescOnce sync.Once
	file_models_tracking_model_proto_rawDescData []byte
)

func file_models_tracking_model_proto_rawDescGZIP() []byte {
	file_models_tracking_model_proto_rawDescOnce.Do(func() {
		file_models_tracking_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_tracking_model_proto_rawDesc), len(file_models_tracking_model_proto_rawDesc)))
	})
	return file_models_tracking_model_proto_rawDescData
}

var file_models_tracking_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_tracking_model_proto_goTypes = []any{
	(*TrackingEvent)(nil),         // 0: trackbox.models.v1.TrackingEvent
	(*Tracking)(nil),              // 1: trackbox.models.v1.Tracking
	(*TrackingCreateInput)(nil),   // 2: trackbox.models.v1.TrackingCreateInput
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_models_tracking_model_proto_depIdxs = []int32{
	3, // 0: trackbox.models.v1.TrackingEvent.event_time:type_name -> google.protobuf.Timestamp
	3, // 1: trackbox.models.v1.TrackingEvent.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: trackbox.models.v1.Tracking.status_at:type_name -> google.protobuf.Timestamp
	3, // 3: trackbox.models.v1.Tracking.last_checked_at:type_name -> google.protobuf.Timestamp
	3, // 4: trackbox.models.v1.Tracking.next_check_at:type_name -> google.protobuf.Timestamp
	3, // 5: trackbox.models.v1.Tracking.created_at:type_name -> google.protobuf.Timestamp
	3, // 6: trackbox.models.v1.Tracking.updated_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_models_tracking_model_proto_init() }
func file_models_tracking_model_proto_init() {
	if File_models_tracking_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_tracking_model_proto_rawDesc), len(file_models_tracking_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_tracking_model_proto_goTypes,
		DependencyIndexes: file_models_tracking_model_proto_depIdxs,
		MessageInfos:      file_models_tracking_model_proto_msgTypes,
	}.Build()
	File_models_tracking_model_proto = out.File
	file_models_tracking_model_proto_goTypes = nil
	file_models_tracking_model_proto_depIdxs = nil
}
