// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockBytesCache is an autogenerated mock type for the BytesCache type
type MockBytesCache struct {
	mock.Mock
}

type MockBytesCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBytesCache) EXPECT() *MockBytesCache_Expecter {
	return &MockBytesCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockBytesCache) Get(ctx context.Context, key string) ([]byte, bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBytesCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBytesCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockBytesCache_Expecter) Get(ctx interface{}, key interface{}) *MockBytesCache_Get_Call {
	return &MockBytesCache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockBytesCache_Get_Call) Run(run func(ctx context.Context, key string)) *MockBytesCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBytesCache_Get_Call) Return(_a0 []byte, _a1 bool, _a2 error) *MockBytesCache_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBytesCache_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, bool, error)) *MockBytesCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockBytesCache) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBytesCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockBytesCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *MockBytesCache_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockBytesCache_Set_Call {
	return &MockBytesCache_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockBytesCache_Set_Call) Run(run func(ctx context.Context, key string, value []byte, ttl time.Duration)) *MockBytesCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockBytesCache_Set_Call) Return(_a0 error) *MockBytesCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBytesCache_Set_Call) RunAndReturn(run func(context.Context, string, []byte, time.Duration) error) *MockBytesCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBytesCache creates a new instance of MockBytesCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBytesCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBytesCache {
	mock := &MockBytesCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
