// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/BearBump/TrackBox/internal/models"
	mock "github.com/stretchr/testify/mock"

	pgtracking "github.com/BearBump/TrackBox/internal/storage/pgtracking"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ApplyTrackingUpdate provides a mock function with given fields: ctx, upd
func (_m *MockRepository) ApplyTrackingUpdate(ctx context.Context, upd pgtracking.TrackingUpdate) error {
	ret := _m.Called(ctx, upd)

	if len(ret) == 0 {
		panic("no return value specified for ApplyTrackingUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtracking.TrackingUpdate) error); ok {
		r0 = rf(ctx, upd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ApplyTrackingUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyTrackingUpdate'
type MockRepository_ApplyTrackingUpdate_Call struct {
	*mock.Call
}

// ApplyTrackingUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - upd pgtracking.TrackingUpdate
func (_e *MockRepository_Expecter) ApplyTrackingUpdate(ctx interface{}, upd interface{}) *MockRepository_ApplyTrackingUpdate_Call {
	return &MockRepository_ApplyTrackingUpdate_Call{Call: _e.mock.On("ApplyTrackingUpdate", ctx, upd)}
}

func (_c *MockRepository_ApplyTrackingUpdate_Call) Run(run func(ctx context.Context, upd pgtracking.TrackingUpdate)) *MockRepository_ApplyTrackingUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtracking.TrackingUpdate))
	})
	return _c
}

func (_c *MockRepository_ApplyTrackingUpdate_Call) Return(_a0 error) *MockRepository_ApplyTrackingUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ApplyTrackingUpdate_Call) RunAndReturn(run func(context.Context, pgtracking.TrackingUpdate) error) *MockRepository_ApplyTrackingUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrGetTrackings provides a mock function with given fields: ctx, items
func (_m *MockRepository) CreateOrGetTrackings(ctx context.Context, items []models.TrackingCreateInput) ([]*models.Tracking, error) {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrGetTrackings")
	}

	var r0 []*models.Tracking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.TrackingCreateInput) ([]*models.Tracking, error)); ok {
		return rf(ctx, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.TrackingCreateInput) []*models.Tracking); ok {
		r0 = rf(ctx, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tracking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.TrackingCreateInput) error); ok {
		r1 = rf(ctx, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateOrGetTrackings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrGetTrackings'
type MockRepository_CreateOrGetTrackings_Call struct {
	*mock.Call
}

// CreateOrGetTrackings is a helper method to define mock.On call
//   - ctx context.Context
//   - items []models.TrackingCreateInput
func (_e *MockRepository_Expecter) CreateOrGetTrackings(ctx interface{}, items interface{}) *MockRepository_CreateOrGetTrackings_Call {
	return &MockRepository_CreateOrGetTrackings_Call{Call: _e.mock.On("CreateOrGetTrackings", ctx, items)}
}

func (_c *MockRepository_CreateOrGetTrackings_Call) Run(run func(ctx context.Context, items []models.TrackingCreateInput)) *MockRepository_CreateOrGetTrackings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.TrackingCreateInput))
	})
	return _c
}

func (_c *MockRepository_CreateOrGetTrackings_Call) Return(_a0 []*models.Tracking, _a1 error) *MockRepository_CreateOrGetTrackings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateOrGetTrackings_Call) RunAndReturn(run func(context.Context, []models.TrackingCreateInput) ([]*models.Tracking, error)) *MockRepository_CreateOrGetTrackings_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrackingsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRepository) GetTrackingsByIDs(ctx context.Context, ids []uint64) ([]*models.Tracking, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackingsByIDs")
	}

	var r0 []*models.Tracking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.Tracking, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.Tracking); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Tracking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetTrackingsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackingsByIDs'
type MockRepository_GetTrackingsByIDs_Call struct {
	*mock.Call
}

// GetTrackingsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint64
func (_e *MockRepository_Expecter) GetTrackingsByIDs(ctx interface{}, ids interface{}) *MockRepository_GetTrackingsByIDs_Call {
	return &MockRepository_GetTrackingsByIDs_Call{Call: _e.mock.On("GetTrackingsByIDs", ctx, ids)}
}

func (_c *MockRepository_GetTrackingsByIDs_Call) Run(run func(ctx context.Context, ids []uint64)) *MockRepository_GetTrackingsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *MockRepository_GetTrackingsByIDs_Call) Return(_a0 []*models.Tracking, _a1 error) *MockRepository_GetTrackingsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetTrackingsByIDs_Call) RunAndReturn(run func(context.Context, []uint64) ([]*models.Tracking, error)) *MockRepository_GetTrackingsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrackingEvents provides a mock function with given fields: ctx, trackingID, limit, offset
func (_m *MockRepository) ListTrackingEvents(ctx context.Context, trackingID uint64, limit int, offset int) ([]*models.TrackingEvent, error) {
	ret := _m.Called(ctx, trackingID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTrackingEvents")
	}

	var r0 []*models.TrackingEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) ([]*models.TrackingEvent, error)); ok {
		return rf(ctx, trackingID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, int) []*models.TrackingEvent); ok {
		r0 = rf(ctx, trackingID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TrackingEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int, int) error); ok {
		r1 = rf(ctx, trackingID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListTrackingEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrackingEvents'
type MockRepository_ListTrackingEvents_Call struct {
	*mock.Call
}

// ListTrackingEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingID uint64
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) ListTrackingEvents(ctx interface{}, trackingID interface{}, limit interface{}, offset interface{}) *MockRepository_ListTrackingEvents_Call {
	return &MockRepository_ListTrackingEvents_Call{Call: _e.mock.On("ListTrackingEvents", ctx, trackingID, limit, offset)}
}

func (_c *MockRepository_ListTrackingEvents_Call) Run(run func(ctx context.Context, trackingID uint64, limit int, offset int)) *MockRepository_ListTrackingEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_ListTrackingEvents_Call) Return(_a0 []*models.TrackingEvent, _a1 error) *MockRepository_ListTrackingEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListTrackingEvents_Call) RunAndReturn(run func(context.Context, uint64, int, int) ([]*models.TrackingEvent, error)) *MockRepository_ListTrackingEvents_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTracking provides a mock function with given fields: ctx, trackingID
func (_m *MockRepository) RefreshTracking(ctx context.Context, trackingID uint64) error {
	ret := _m.Called(ctx, trackingID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTracking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, trackingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RefreshTracking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTracking'
type MockRepository_RefreshTracking_Call struct {
	*mock.Call
}

// RefreshTracking is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingID uint64
func (_e *MockRepository_Expecter) RefreshTracking(ctx interface{}, trackingID interface{}) *MockRepository_RefreshTracking_Call {
	return &MockRepository_RefreshTracking_Call{Call: _e.mock.On("RefreshTracking", ctx, trackingID)}
}

func (_c *MockRepository_RefreshTracking_Call) Run(run func(ctx context.Context, trackingID uint64)) *MockRepository_RefreshTracking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockRepository_RefreshTracking_Call) Return(_a0 error) *MockRepository_RefreshTracking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RefreshTracking_Call) RunAndReturn(run func(context.Context, uint64) error) *MockRepository_RefreshTracking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
