// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: trackings_api/trackings.proto

package trackings_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	models "trackbox/internal/pb/models"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTrackingsRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Items         []*models.TrackingCreateInput `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackingsRequest) Reset() {
	*x = CreateTrackingsRequest{}
	mi := &file_trackings_api_trackings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackingsRequest) ProtoMessage() {}

func (x *CreateTrackingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackings_api_trackings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackingsRequest.ProtoReflect.Descriptor instead.
func (*CreateTrackingsRequest) Descriptor() ([]byte, []int) {
	return file_trackings_api_trackings_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTrackingsRequest) GetItems() []*models.TrackingCreateInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateTrackingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trackings     []*models.Tracking     `protobuf:"bytes,1,rep,name=trackings,proto3" json:"trackings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackingsResponse) Reset() {
	*x = CreateTrackingsResponse{}
	mi := &file_trackings_api_trackings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackingsResponse) ProtoMessage() {}

func (x *CreateTrackingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trackings_api_trackings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackingsResponse.ProtoReflect.Descriptor instead.
func (*CreateTrackingsResponse) Descriptor() ([]byte, []int) {
	return file_trackings_api_trackings_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrackingsResponse) GetTrackings() []*models.Tracking {
	if x != nil {
		return x.Trackings
	}
	return nil
}

type GetTrackingsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingsByIdsRequest) Reset() {
	*x = GetTrackingsByIdsRequest{}
	mi := &file_trackings_api_trackings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingsByIdsRequest) ProtoMessage() {}

func (x *GetTrackingsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackings_api_trackings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_trackings_api_trackings_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrackingsByIdsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTrackingsByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trackings     []*models.Tracking     `protobuf:"bytes,1,rep,name=trackings,proto3" json:"trackings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingsByIdsResponse) Reset() {
	*x = GetTrackingsByIdsResponse{}
	mi := &file_trackings_api_trackings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingsByIdsResponse) ProtoMessage() {}

func (x *GetTrackingsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trackings_api_trackings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetTrackingsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_trackings_api_trackings_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrackingsByIdsResponse) GetTrackings() []*models.Tracking {
	if x != nil {
		return x.Trackings
	}
	return nil
}

type ListTrackingEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingId    uint64                 `protobuf:"varint,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrackingEventsRequest) Reset() {
	*x = ListTrackingEventsRequest{}
	mi := &file_trackings_api_trackings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrackingEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrackingEventsRequest) ProtoMessage() {}

func (x *ListTrackingEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackings_api_trackings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrackingEventsRequest.ProtoReflect.Descriptor instead.
func (*ListTrackingEventsRequest) Descriptor() ([]byte, []int) {
	return file_trackings_api_trackings_proto_rawDescGZIP(), []int{4}
}

func (x *ListTrackingEventsRequest) GetTrackingId() uint64 {
	if x != nil {
		return x.TrackingId
	}
	return 0
}

func (x *ListTrackingEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTrackingEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTrackingEventsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Events        []*models.TrackingEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrackingEventsResponse) Reset() {
	*x = ListTrackingEventsResponse{}
	mi := &file_trackings_api_trackings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrackingEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrackingEventsResponse) ProtoMessage() {}

func (x *ListTrackingEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trackings_api_trackings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrackingEventsResponse.ProtoReflect.Descriptor instead.
func (*ListTrackingEventsResponse) Descriptor() ([]byte, []int) {
	return file_trackings_api_trackings_proto_rawDescGZIP(), []int{5}
}

func (x *ListTrackingEventsResponse) GetEvents() []*models.TrackingEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RefreshTrackingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingId    uint64                 `protobuf:"varint,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTrackingRequest) Reset() {
	*x = RefreshTrackingRequest{}
	mi := &file_trackings_api_trackings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTrackingRequest) ProtoMessage() {}

func (x *RefreshTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trackings_api_trackings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTrackingRequest.ProtoReflect.Descriptor instead.
func (*RefreshTrackingRequest) Descriptor() ([]byte, []int) {
	return file_trackings_api_trackings_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTrackingRequest) GetTrackingId() uint64 {
	if x != nil {
		return x.TrackingId
	}
	return 0
}

var File_trackings_api_trackings_proto protoreflect.FileDescriptor

const file_trackings_api_trackings_proto_rawDesc = "" +
	"\n" +
	"\x1dtrackings_api/trackings.proto\x12\x15trackbox.trackings.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bmodels/tracking_model.proto\"W\n" +
	"\x16CreateTrackingsRequest\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.trackbox.models.v1.TrackingCreateInputR\x05items\"U\n" +
	"\x17CreateTrackingsResponse\x12:\n" +
	"\ttrackings\x18\x01 \x03(\v2\x1c.trackbox.models.v1.TrackingR\ttrackings\",\n" +
	"\x18GetTrackingsByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"W\n" +
	"\x19GetTrackingsByIdsResponse\x12:\n" +
	"\ttrackings\x18\x01 \x03(\v2\x1c.trackbox.models.v1.TrackingR\ttrackings\"j\n" +
	"\x19ListTrackingEventsRequest\x12\x1f\n" +
	"\vtracking_id\x18\x01 \x01(\x04R\n" +
	"trackingId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"W\n" +
	"\x1aListTrackingEventsResponse\x129\n" +
	"\x06events\x18\x01 \x03(\v2!.trackbox.models.v1.TrackingEventR\x06events\"9\n" +
	"\x16RefreshTrackingRequest\x12\x1f\n" +
	"\vtracking_id\x18\x01 \x01(\x04R\n" +
	"trackingId2\xe4\x04\n" +
	"\x10TrackingsService\x12\x87\x01\n" +
	"\x0fCreateTrackings\x12-.trackbox.trackings.v1.CreateTrackingsRequest\x1a..trackbox.trackings.v1.CreateTrackingsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/trackings\x12\x98\x01\n" +
	"\x11GetTrackingsByIds\x12/.trackbox.trackings.v1.GetTrackingsByIdsRequest\x1a0.trackbox.trackings.v1.GetTrackingsByIdsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/trackings/get-by-ids\x12\xa2\x01\n" +
	"\x12ListTrackingEvents\x120.trackbox.trackings.v1.ListTrackingEventsRequest\x1a1.trackbox.trackings.v1.ListTrackingEventsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/trackings/{tracking_id}/events\x12\x85\x01\n" +
	"\x0fRefreshTracking\x12-.trackbox.trackings.v1.RefreshTrackingRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%:\x01*\" /trackings/{tracking_id}/refreshB$Z\"trackbox/internal/pb/trackings_apib\x06proto3"

var (
	file_trackings_api_trackings_proto_rawDescOnce sync.Once
	file_trackings_api_trackings_proto_rawDescData []byte
)

func file_trackings_api_trackings_proto_rawDescGZIP() []byte {
	file_trackings_api_trackings_proto_rawDescOnce.Do(func() {
		file_trackings_api_trackings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trackings_api_trackings_proto_rawDesc), len(file_trackings_api_trackings_proto_rawDesc)))
	})
	return file_trackings_api_trackings_proto_rawDescData
}

var file_trackings_api_trackings_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_trackings_api_trackings_proto_goTypes = []any{
	(*CreateTrackingsRequest)(nil),     // 0: trackbox.trackings.v1.CreateTrackingsRequest
	(*CreateTrackingsResponse)(nil),    // 1: trackbox.trackings.v1.CreateTrackingsResponse
	(*GetTrackingsByIdsRequest)(nil),   // 2: trackbox.trackings.v1.GetTrackingsByIdsRequest
	(*GetTrackingsByIdsResponse)(nil),  // 3: trackbox.trackings.v1.GetTrackingsByIdsResponse
	(*ListTrackingEventsRequest)(nil),  // 4: trackbox.trackings.v1.ListTrackingEventsRequest
	(*ListTrackingEventsResponse)(nil), // 5: trackbox.trackings.v1.ListTrackingEventsResponse
	(*RefreshTrackingRequest)(nil),     // 6: trackbox.trackings.v1.RefreshTrackingRequest
	(*models.TrackingCreateInput)(nil), // 7: trackbox.models.v1.TrackingCreateInput
	(*models.Tracking)(nil),            // 8: trackbox.models.v1.Tracking
	(*models.TrackingEvent)(nil),       // 9: trackbox.models.v1.TrackingEvent
	(*emptypb.Empty)(nil),              // 10: google.protobuf.Empty
}
var file_trackings_api_trackings_proto_depIdxs = []int32{
	7,  // 0: trackbox.trackings.v1.CreateTrackingsRequest.items:type_name -> trackbox.models.v1.TrackingCreateInput
	8,  // 1: trackbox.trackings.v1.CreateTrackingsResponse.trackings:type_name -> trackbox.models.v1.Tracking
	8,  // 2: trackbox.trackings.v1.GetTrackingsByIdsResponse.trackings:type_name -> trackbox.models.v1.Tracking
	9,  // 3: trackbox.trackings.v1.ListTrackingEventsResponse.events:type_name -> trackbox.models.v1.TrackingEvent
	0,  // 4: trackbox.trackings.v1.TrackingsService.CreateTrackings:input_type -> trackbox.trackings.v1.CreateTrackingsRequest
	2,  // 5: trackbox.trackings.v1.TrackingsService.GetTrackingsByIds:input_type -> trackbox.trackings.v1.GetTrackingsByIdsRequest
	4,  // 6: trackbox.trackings.v1.TrackingsService.ListTrackingEvents:input_type -> trackbox.trackings.v1.ListTrackingEventsRequest
	6,  // 7: trackbox.trackings.v1.TrackingsService.RefreshTracking:input_type -> trackbox.trackings.v1.RefreshTrackingRequest
	1,  // 8: trackbox.trackings.v1.TrackingsService.CreateTrackings:output_type -> trackbox.trackings.v1.CreateTrackingsResponse
	3,  // 9: trackbox.trackings.v1.TrackingsService.GetTrackingsByIds:output_type -> trackbox.trackings.v1.GetTrackingsByIdsResponse
	5,  // 10: trackbox.trackings.v1.TrackingsService.ListTrackingEvents:output_type -> trackbox.trackings.v1.ListTrackingEventsResponse
	10, // 11: trackbox.trackings.v1.TrackingsService.RefreshTracking:output_type -> google.protobuf.Empty
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_trackings_api_trackings_proto_init() }
func file_trackings_api_trackings_proto_init() {
	if File_trackings_api_trackings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trackings_api_trackings_proto_rawDesc), len(file_trackings_api_trackings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trackings_api_trackings_proto_goTypes,
		DependencyIndexes: file_trackings_api_trackings_proto_depIdxs,
		MessageInfos:      file_trackings_api_trackings_proto_msgTypes,
	}.Build()
	File_trackings_api_trackings_proto = out.File
	file_trackings_api_trackings_proto_goTypes = nil
	file_trackings_api_trackings_proto_depIdxs = nil
}
