// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: trackings_api/trackings.proto

package trackings_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackingsService_CreateTrackings_FullMethodName    = "/trackbox.trackings.v1.TrackingsService/CreateTrackings"
	TrackingsService_GetTrackingsByIds_FullMethodName  = "/trackbox.trackings.v1.TrackingsService/GetTrackingsByIds"
	TrackingsService_ListTrackingEvents_FullMethodName = "/trackbox.trackings.v1.TrackingsService/ListTrackingEvents"
	TrackingsService_RefreshTracking_FullMethodName    = "/trackbox.trackings.v1.TrackingsService/RefreshTracking"
)

// TrackingsServiceClient is the client API for TrackingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackingsServiceClient interface {
	CreateTrackings(ctx context.Context, in *CreateTrackingsRequest, opts ...grpc.CallOption) (*CreateTrackingsResponse, error)
	GetTrackingsByIds(ctx context.Context, in *GetTrackingsByIdsRequest, opts ...grpc.CallOption) (*GetTrackingsByIdsResponse, error)
	ListTrackingEvents(ctx context.Context, in *ListTrackingEventsRequest, opts ...grpc.CallOption) (*ListTrackingEventsResponse, error)
	RefreshTracking(ctx context.Context, in *RefreshTrackingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type trackingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackingsServiceClient(cc grpc.ClientConnInterface) TrackingsServiceClient {
	return &trackingsServiceClient{cc}
}

func (c *trackingsServiceClient) CreateTrackings(ctx context.Context, in *CreateTrackingsRequest, opts ...grpc.CallOption) (*CreateTrackingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTrackingsResponse)
	err := c.cc.Invoke(ctx, TrackingsService_CreateTrackings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingsServiceClient) GetTrackingsByIds(ctx context.Context, in *GetTrackingsByIdsRequest, opts ...grpc.CallOption) (*GetTrackingsByIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackingsByIdsResponse)
	err := c.cc.Invoke(ctx, TrackingsService_GetTrackingsByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingsServiceClient) ListTrackingEvents(ctx context.Context, in *ListTrackingEventsRequest, opts ...grpc.CallOption) (*ListTrackingEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrackingEventsResponse)
	err := c.cc.Invoke(ctx, TrackingsService_ListTrackingEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingsServiceClient) RefreshTracking(ctx context.Context, in *RefreshTrackingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TrackingsService_RefreshTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackingsServiceServer is the server API for TrackingsService service.
// All implementations must embed UnimplementedTrackingsServiceServer
// for forward compatibility.
type TrackingsServiceServer interface {
	CreateTrackings(context.Context, *CreateTrackingsRequest) (*CreateTrackingsResponse, error)
	GetTrackingsByIds(context.Context, *GetTrackingsByIdsRequest) (*GetTrackingsByIdsResponse, error)
	ListTrackingEvents(context.Context, *ListTrackingEventsRequest) (*ListTrackingEventsResponse, error)
	RefreshTracking(context.Context, *RefreshTrackingRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTrackingsServiceServer()
}

// UnimplementedTrackingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackingsServiceServer struct{}

func (UnimplementedTrackingsServiceServer) CreateTrackings(context.Context, *CreateTrackingsRequest) (*CreateTrackingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrackings not implemented")
}
func (UnimplementedTrackingsServiceServer) GetTrackingsByIds(context.Context, *GetTrackingsByIdsRequest) (*GetTrackingsByIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackingsByIds not implemented")
}
func (UnimplementedTrackingsServiceServer) ListTrackingEvents(context.Context, *ListTrackingEventsRequest) (*ListTrackingEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrackingEvents not implemented")
}
func (UnimplementedTrackingsServiceServer) RefreshTracking(context.Context, *RefreshTrackingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshTracking not implemented")
}
func (UnimplementedTrackingsServiceServer) mustEmbedUnimplementedTrackingsServiceServer() {}
func (UnimplementedTrackingsServiceServer) testEmbeddedByValue()                          {}

// UnsafeTrackingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackingsServiceServer will
// result in compilation errors.
type UnsafeTrackingsServiceServer interface {
	mustEmbedUnimplementedTrackingsServiceServer()
}

func RegisterTrackingsServiceServer(s grpc.ServiceRegistrar, srv TrackingsServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackingsService_ServiceDesc, srv)
}

func _TrackingsService_CreateTrackings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrackingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingsServiceServer).CreateTrackings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingsService_CreateTrackings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingsServiceServer).CreateTrackings(ctx, req.(*CreateTrackingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingsService_GetTrackingsByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackingsByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingsServiceServer).GetTrackingsByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingsService_GetTrackingsByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingsServiceServer).GetTrackingsByIds(ctx, req.(*GetTrackingsByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingsService_ListTrackingEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrackingEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingsServiceServer).ListTrackingEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingsService_ListTrackingEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingsServiceServer).ListTrackingEvents(ctx, req.(*ListTrackingEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingsService_RefreshTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingsServiceServer).RefreshTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackingsService_RefreshTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingsServiceServer).RefreshTracking(ctx, req.(*RefreshTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackingsService_ServiceDesc is the grpc.ServiceDesc for TrackingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trackbox.trackings.v1.TrackingsService",
	HandlerType: (*TrackingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrackings",
			Handler:    _TrackingsService_CreateTrackings_Handler,
		},
		{
			MethodName: "GetTrackingsByIds",
			Handler:    _TrackingsService_GetTrackingsByIds_Handler,
		},
		{
			MethodName: "ListTrackingEvents",
			Handler:    _TrackingsService_ListTrackingEvents_Handler,
		},
		{
			MethodName: "RefreshTracking",
			Handler:    _TrackingsService_RefreshTracking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trackings_api/trackings.proto",
}
